layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username

topics:
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: 
  
  - name: ASP.NET
    web_url: https://github.com/topics/aspnet
    image_url: 
    
  - name: Unity
    web_url: https://github.com/topics/unity
    image_url:
    
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url:
  
  - name: React
    web_url: https://github.com/topics/react
    image_url:
    
  - name: Angular
    web_url: https://github.com/topics/angular
    image_url:
    
  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url:
    
  - name: PHP
    web_url: https://github.com/topics/php
    image_url:
    
  - name: MySQL
    web_url: https://github.com/topics/mysql
    image_url:
    
  - name: Python
    web_url: https://github.com/topics/python
    image_url:
